/* Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
 * The first ten pentagonal numbers are:
 *
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
 * 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
 * difference are pentagonal and D = |Pk − Pj| is minimised; what is the value
 * of D?
 */

fn main() {
    let pnums = pentagonal_gen(2500);
    let mut tpnums = vec![false; *pnums.last().unwrap() as usize * 2];
    for &n in &pnums { tpnums[n as usize] = true; }
    let mut dmin = usize::max_value();
    for i in 0..pnums.len() - 1 {
        for j in i + 1..pnums.len() {
            let sum = pnums[i] + pnums[j];
            let diff = pnums[j] - pnums[i];
            if tpnums[sum] && tpnums[diff] && diff < dmin {
                dmin = diff;
            }
        }
    }
    println!("{}", dmin);
}

fn pentagonal_gen(n: usize) -> Vec<usize> {
    let mut pnums = Vec::with_capacity(n);
    pnums.push(1);
    let mut pn = 1;
    let mut inc = 4;
    for _ in 1..n {
        pn += inc;
        pnums.push(pn);
        inc += 3;
    }
    pnums
}
