/* Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulæ:
 *
 * Triangle		Tn=n(n+1)/2		1, 3, 6, 10, 15, ...
 * Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
 * Hexagonal	Hn=n(2n−1)		1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */



fn main() {
    let mut penta = (166..).map(|n| n * (3 * n - 1) / 2);
    let mut hexa = (144..).map(|n| n * (2 * n - 1));

    let mut p = penta.next().unwrap();
    let mut h: u32;
    loop {
        h = hexa.next().unwrap();
        while p < h { p = penta.next().unwrap(); }
        if p == h { break }
    }
    println!("{}", p);
}
